//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillBoardsManagement.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class lk_catagory_rates
    {
        public int Id { get; set; }
        public string Road { get; set; }
        public string Catagory { get; set; }
        public string SubCatagory { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<bool> IsBrand { get; set; }
    }
}
