//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillBoardsManagement.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class lk_publicity_float
    {
        public int Id { get; set; }
        public string Catagory { get; set; }
        public Nullable<decimal> PerDay { get; set; }
        public Nullable<decimal> Perweek { get; set; }
        public Nullable<decimal> PerTwoWeek { get; set; }
        public Nullable<decimal> PerMonth { get; set; }
    }
}
