//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillBoardsManagement.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class lk_Region
    {
        public int Id { get; set; }
        public string Contractor { get; set; }
        public string Area { get; set; }
        public string Region { get; set; }
        public string Region_on_pdf { get; set; }
        public Nullable<int> amount_position_X { get; set; }
        public Nullable<int> amount_position_Y { get; set; }
        public Nullable<int> name_position_X { get; set; }
        public Nullable<int> name_position_Y { get; set; }
        public Nullable<int> date_position_X { get; set; }
        public Nullable<int> date_position_Y { get; set; }
        public Nullable<int> bill_id_Y { get; set; }
        public Nullable<int> bill_id_X { get; set; }
        public Nullable<int> billApp_Y { get; set; }
        public Nullable<int> billApp_X { get; set; }
        public Nullable<int> address_X { get; set; }
        public Nullable<int> address_Y { get; set; }
        public string PdfFileName { get; set; }
    }
}
