//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillBoardsManagement.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class lk_town
    {
        public int Id { get; set; }
        public string Town { get; set; }
        public string Contractor { get; set; }
        public string Area { get; set; }
        public string Region { get; set; }
        public string Region_on_pdf { get; set; }
    }
}
