//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillBoardsManagement.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BBMSEntities : DbContext
    {
        public BBMSEntities()
            : base("name=BBMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<lk_catagory_rates> lk_catagory_rates { get; set; }
        public virtual DbSet<lk_role> lk_role { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<lk_BillAppender> lk_BillAppender { get; set; }
        public virtual DbSet<lk_publicity_float> lk_publicity_float { get; set; }
        public virtual DbSet<lk_Region> lk_Region { get; set; }
        public virtual DbSet<lk_rates> lk_rates { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
    }
}
